CREATE TABLE ProductionOrders (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  FinishedGoodId INT NOT NULL,
  QuantityToProduce DECIMAL(10,2) NOT NULL,
  ProductionDate DATETIME NOT NULL,
  IsCompleted BOOLEAN DEFAULT FALSE,
  FOREIGN KEY (FinishedGoodId) REFERENCES InventoryItems(Id) ON DELETE CASCADE,
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedBy VARCHAR(100) DEFAULT NULL,
  UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UpdatedBy VARCHAR(100) DEFAULT NULL
);

CREATE TABLE ProductionConsumption (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  ProductionOrderId INT NOT NULL,
  RawMaterialId INT NOT NULL,
  QuantityUsed DECIMAL(10,2) NOT NULL,
  UsedDate DATETIME NOT NULL,
  FOREIGN KEY (ProductionOrderId) REFERENCES ProductionOrders(Id) ON DELETE CASCADE,
  FOREIGN KEY (RawMaterialId) REFERENCES InventoryItems(Id) ON DELETE CASCADE,
  CreatedOn DATETIME DEFAULT CURRENT_TIMESTAMP,
  CreatedBy VARCHAR(100) DEFAULT NULL,
  UpdatedOn DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UpdatedBy VARCHAR(100) DEFAULT NULL
);

-- WAREHOUSE & INVENTORY MOVEMENT STRUCTURE

CREATE TABLE Warehouses (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  LocationName VARCHAR(100) NOT NULL,
  Address VARCHAR(255) NOT NULL
);

CREATE TABLE WarehouseBins (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  BinCode VARCHAR(50) NOT NULL,
  WarehouseId INT NOT NULL,
  FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id) ON DELETE CASCADE
);

CREATE TABLE InventoryMovements (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  InventoryItemId INT NOT NULL,
  WarehouseId INT NOT NULL,
  MovementDate DATETIME NOT NULL,
  Quantity INT NOT NULL,
  MovementType ENUM('PurchaseIn', 'SaleOut', 'TransferIn', 'TransferOut', 'AdjustmentIn', 'AdjustmentOut') NOT NULL,
  Notes TEXT,
  FOREIGN KEY (InventoryItemId) REFERENCES InventoryItems(Id) ON DELETE CASCADE,
  FOREIGN KEY (WarehouseId) REFERENCES Warehouses(Id) ON DELETE CASCADE
);

CREATE TABLE InventoryTransfers (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  InventoryItemId INT NOT NULL,
  FromWarehouseId INT NOT NULL,
  ToWarehouseId INT NOT NULL,
  Quantity INT NOT NULL,
  TransferDate DATETIME NOT NULL,
  FOREIGN KEY (InventoryItemId) REFERENCES InventoryItems(Id) ON DELETE CASCADE,
  FOREIGN KEY (FromWarehouseId) REFERENCES Warehouses(Id) ON DELETE CASCADE,
  FOREIGN KEY (ToWarehouseId) REFERENCES Warehouses(Id) ON DELETE CASCADE
);

-- PURCHASE ORDER STRUCTURE

CREATE TABLE Suppliers (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  ContactPerson VARCHAR(100),
  Email VARCHAR(100),
  Phone VARCHAR(50),
  Address VARCHAR(255)
);

CREATE TABLE PurchaseOrders (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  OrderNumber VARCHAR(50) NOT NULL,
  OrderDate DATETIME NOT NULL,
  ExpectedDeliveryDate DATETIME,
  SupplierId INT NOT NULL,
  Status ENUM('Draft', 'Ordered', 'Received', 'Cancelled') NOT NULL,
  FOREIGN KEY (SupplierId) REFERENCES Suppliers(Id) ON DELETE CASCADE
);

CREATE TABLE PurchaseOrderLines (
  Id INT PRIMARY KEY AUTO_INCREMENT,
  PurchaseOrderId INT NOT NULL,
  InventoryItemId INT NOT NULL,
  Quantity INT NOT NULL,
  UnitPrice DECIMAL(10,2) NOT NULL,
  Notes TEXT,
  FOREIGN KEY (PurchaseOrderId) REFERENCES PurchaseOrders(Id) ON DELETE CASCADE,
  FOREIGN KEY (InventoryItemId) REFERENCES InventoryItems(Id) ON DELETE CASCADE
);
