INSERT INTO `app_rights` (`id`, `name`, `group_by`, `CreatedOn`, `CreatedBy`)
VALUES
(1, 'View Dashboard', 'Dashboard', NOW(), 'system'),
(2, 'View Orders', 'Orders', NOW(), 'system'),
(3, 'Add Orders', 'Orders', NOW(), 'system'),
(4, 'Update Orders', 'Orders', NOW(), 'system'),
(5, 'Delete Orders', 'Orders', NOW(), 'system'),
(6, 'Re-Order', 'Orders', NOW(), 'system'),
(7, 'View Product', 'Products', NOW(), 'system'),
(8, 'Add Product', 'Products', NOW(), 'system'),
(9, 'Update Product', 'Products', NOW(), 'system'),
(10, 'Delete Product', 'Products', NOW(), 'system'),
(11, 'Change Product Status', 'Products', NOW(), 'system'),
(12, 'View Product Definition', 'Product Definitions', NOW(), 'system'),
(13, 'Add Product Definition', 'Product Definitions', NOW(), 'system'),
(14, 'Update Product Definition', 'Product Definitions', NOW(), 'system'),
(15, 'Delete Product Definition', 'Product Definitions', NOW(), 'system'),
(16, 'View Inventory', 'Inventory', NOW(), 'system'),
(17, 'Add Inventory', 'Inventory', NOW(), 'system'),
(18, 'Update Inventory', 'Inventory', NOW(), 'system'),
(19, 'Delete Inventory', 'Inventory', NOW(), 'system'),
(20, 'View Shipment', 'Shipments', NOW(), 'system'),
(21, 'Add Shipment', 'Shipments', NOW(), 'system'),
(22, 'Update Shipment', 'Shipments', NOW(), 'system'),
(23, 'Delete Shipment', 'Shipments', NOW(), 'system'),
(24, 'View Audit Logs', 'Audit Logs', NOW(), 'system'),
(25, 'View Admin Settings', 'Admin Settings', NOW(), 'system'),
(26, 'Add Admin Settings', 'Admin Settings', NOW(), 'system'),
(27, 'Update Admin Settings', 'Admin Settings', NOW(), 'system'),
(28, 'Delete Admin Settings', 'Admin Settings', NOW(), 'system');
